### ISSUE TITLE
acvm_js gets stuck after solving some pedersen operations

### ISSUE THREAD

**Issue by sirasistant** [noir-lang/acvm#517]
### Aim

While trying to update aztec to the current ACVM, I realized that functions were getting stuck and I was getting `Error: failed to solve blackbox function: pedersen, reason: Trying to call bbmalloc resulted in an error`. Then I tried to reproduce it in an acvm_js test, and added this in execute_circuit.test.ts
```typescript
it.only("successfully executes 500 circuits with same backend", async function () {
  this.timeout(100000);

  // chose pedersen op here because it is the one with slow initialization
  // that led to the decision to pull backend initialization into a separate
  // function/wasmbind
  const solver: WasmBlackBoxFunctionSolver = await createBlackBoxSolver();

  const { bytecode, initialWitnessMap, expectedWitnessMap } = await import(
    "../shared/pedersen"
  );

  for (let i = 0; i < 500; i++) {
    console.log("Iteration", i);
    const solvedWitness = await executeCircuitWithBlackBoxSolver(
      solver,
      bytecode,
      initialWitnessMap,
      () => {
        throw Error("unexpected oracle");
      }
    );
    console.log("Solved!");

    expect(solvedWitness).to.be.deep.eq(expectedWitnessMap);
  }
});
```

### Expected Behavior

The test should pass

### Bug

This tests starts getting stuck at iteration 28 after this commit https://github.com/noir-lang/acvm/commit/a1d4b71256dfbf1e883e770dd9c45479235aa860 when barretenberg solver was implemented here, in the ACVM. In the previous commit, it passes taking 3.5 seconds.

### To Reproduce

1.
2.
3.
4.

### Would you like to submit a PR for this Issue?

No

**Comment by sirasistant** [comment]
This is also happening in aztec running a low number of circuits with multiple pedersen operations

**Comment by kevaundray** [comment]
Managed to repoduce and fix it in this PR https://github.com/noir-lang/acvm/pull/518

The issue was that our new WASM binary requires a call to _initialize for WASI. This was not the case before. If this is not done, then the module does not behave as expected, in our case it was allowing us to make 29 pedersen calls before panicking in the bbmalloc procedure.

I'm still not sure why it even allows you to make calls on the binary without setting up the proper resources with `_initialize`, if they are deemed needed.
